services:
  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ecmp-admin
      POSTGRES_PASSWORD: E8GSiy513zyMy9d?F1jf
      POSTGRES_ROOT_PASSWORD: E8GSiy513zyMy9d?F1jf
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U ecmp-admin" ]
      interval: 5s
      retries: 3
    networks:
      - ecmp-network
networks:
  ecmp-network: