services:
  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U developer" ]
      interval: 5s
      retries: 3
    networks:
      - ecmp-network
  backend:
    container_name: ecmp-api
    build:
      context: ecmp-dev/.
      dockerfile: Dockerfile
    image: ecmp-dev:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_PROFILES_ACTIVE: dev
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://keycloak:8081/realms/ECMP-API-DEV
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecmp-network
  frontend:
    container_name: ecmp-frontend
    build:
      context: ecmp-frontend/.
      dockerfile: Dockerfilev1
    image: ecmp-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecmp-network
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
    ports:
      - "8081:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_USERNAME: developer
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecmp-network
networks:
  ecmp-network: