spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ECMP-API-DEV
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  application:
    name: "ecmp-api"
  datasource:
    url: jdbc:postgresql://<database_name>:<database_port>/<database_table_name>
    username: <database_user>
    password: <database_password>
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true
    show-sql: false
    database: postgresql
    generate-ddl: true
  profiles:
    active: <active_profile>
cors:
  allowedOrigins: <allowed_origins>