spring:
  application:
    name: "ecmp-dev"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: <postgres_user>
    password: <postgres_password>
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true
    show-sql: true
    database: postgresql
application:
  security:
    jwt:
      secret-key: <jwt-key-signature>

cors:
  allowedOrigins: http://localhost/,http://localhost:4200/
