name: ECMP UI Pipeline

on:
  push:
    branches:
      - main
      - feature/**
      - testing/**
    paths:
      - ecmp-frontend/**
      - .github/workflows/**
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  build-image:
    name: Build FE Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ecmp-frontend
          file: ecmp-frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecmp-frontend:latest